# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- main

jobs:
- job: Node_Install
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

- job: Package_Install
  dependsOn: Node_Install
  steps:
    - script: npm install
      displayName: 'npm install'

- job: Lint_Test
  dependsOn: Package_Install
  steps:
    - script: npm run lint
      displayName: 'test lint'

- job: Build
  dependsOn: Package_Install
  steps:
    - script: npm run vite:build
      displayName: 'vite build'

- job: Testing
  dependsOn: Build
  steps:
    - script: |
        npm run test:unit
      displayName: 'unit testing'

