name: Deployment Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  avoid_redudancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  
  download_cache_packages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: download download
        run: npm ci
      - name: Cache node modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules
          retention-days: 1

  lint:
    runs-on: ubuntu-18.04
    needs: download_cache_packages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-18.04
    needs: download_cache_packages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules
      - name: Build
        run: npm run vite:build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"
      - uses: actions/download-artifact@v2
        with:
          name: node_modules
          path: node_modules
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test:unit

  # e2e:
  #   needs: [lint, build]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v2
  #       with:
  #         cache: 'npm'
  #         node-version: '14'
  #     - name: Install dependencies
  #       run: npm ci
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: dist
  #         path: dist
  #     - name: E2E tests
  #       uses: cypress-io/github-action@v2
  #       with:
  #         command: npm run test:e2e
  #         start: npm run start-test
  #         wait-on: http://localhost:5000

  deploy:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy Develop to firebase hosting
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy develop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy prod to firebase hosting
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_UTL_APP_JUEGOS }}"
          projectId: utl-app-juegos
          channelId: live
